### ISSUE TITLE
Remove deleted accounts

### ISSUE THREAD

**Issue by Belzedar94** [freopen/chess-erdos#2]
It would be nice to remove games involving deleted accounts, because they were most likely cheating.

**Comment by freopen** [comment]
Unfortunately it's impossible to detect closed accounts from the information available in Lichess Database.

**Comment by freopen** [comment]
1. It's not scalable. I can't call API for every lichess user.
2. There are users that beat a GM, lost to a 800 rating and play for many
years after that without being banned.
