### ISSUE TITLE
Provide installation instructions

### ISSUE THREAD

**Issue by tsaklidis** [freopen/chess-erdos#3]
@freopen 
Nice project, I wanted to contribute with some styling for the username input in order to be more clear etc.

You have to provide some info how to setup the project locally in order someone can write code and debug.
I tried to install it with no success.
 
![image](https://user-images.githubusercontent.com/7034649/169552713-8c65d93b-a4d7-4738-a754-2b831ee9fab4.png)

Also I was not able to find any info about the required "rkyvdb"

**Comment by freopen** [comment]
Yeah, it depends on another project I'm working on and which is not ready
to be public yet. I'll provide the instructions once it's ready. Please
note that I do not intend to accept any pull requests bigger than a typo
fix. I started this project with an intention to try out approaches I would
like to try out.

For styling: I'm currently working on replacing the whole styling system
from UnoCSS to PostCSS so your contributions will most probably disappear
soon anyway.

**Comment by tsaklidis** [comment]
I see, thank you for the answer, keep on working on this project.
