### ISSUE TITLE
Usernames that are #0

### ISSUE THREAD

**Issue by igroti** [freopen/chess-erdos#8]
What usernames are being used to calculate chains? Magnus has had many aliases. Perhaps we should be trying them all and finding the shortest chain among them all? Perhaps this is already being done, but I couldn't find a way to check...

Thanks

**Comment by freopen** [comment]
Unless we have a sure way to identify the full list of usernames and confirm that each one actually belongs to Magnus - I prefer to keep just the main one at #0 just for the simplicity and consistency. It's also tricky technically, if some new username is confirmed - I have to reprocess everything so the past games of the newly discovered username are taken into account.

**Comment by splakish** [comment]
Many are known, but ok. Would be nice, but I can understand if not doable.
Some examples:
- [@DrDrunkenstein](https://lichess.org/@/DrDrunkenstein)
- [@DrNykterstein](https://lichess.org/@/DrNykterstein)
- [@STL_Carlsen](https://lichess.org/@/STL_Carlsen)
- [@MagnusCarlsen](https://lichess.org/@/MagnusCarlsen)
- [@DannytheDonkey](https://lichess.org/@/DannytheDonkey)
- [@manwithavan](https://lichess.org/@/manwithavan)
- [@damnsaltythatsport](https://lichess.org/@/damnsaltythatsport)
- [@DrGrekenstein](https://lichess.org/@/DrGrekenstein)
- [@damnsaltythatsport](https://lichess.org/@/damnsaltythatsport)
